language: php

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION='2.8.*'

sudo: false

cache:
  directory:
    - .phpunit
    - $HOME/.composer/cache/files

before_install:
  - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi

install:
  - composer update $COMPOSER_FLAGS --prefer-dist

script:
  - ./phpunit
